### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Rosabis** [shinovon/KEmulator#70] opened 2024-09-08 02:43 UTC
The memory view function of the multi-platform version of the KE is broken, and it cannot display images and sounds correctly.
![图片](https://github.com/user-attachments/assets/68482457-80d3-4c6d-a35e-78b195190bfe)

**Comment by shinovon** [comment] 2024-09-08 15:18
It is caused by Java 9+ limitations in reflection, probably won't be fixed

**Comment by klaxons1** [comment] 2024-10-23 11:44
@Rosabis launch the emu with following arguments: 
java --add-opens java.base/java.io=ALL-UNNAMED --enable-native-access=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/sun.misc=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED -jar path/to/KEmulator.jar path/to/game.jar

**Comment by shinovon** [comment] 2024-10-23 15:28
0d006dee88aeae324f7c350b5935aadbcd7a1e77 related

**Comment by shinovon** [comment] 2024-11-12 04:44
Closed by 0d006dee88aeae324f7c350b5935aadbcd7a1e77, 24876bfb2d2436da3d57f5677652c8ff4d10f87e

**Closed by shinovon** 2024-11-12 04:44 UTC
Labels: area:x64
